services:
  ng-cash-postgres-production:
    container_name: ng-cash-postgres-production
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    ports: 
      - 5433:5432
    volumes:
    - postgres:/var/lib/postgresql/data

  ng-cash-backend-application: 
    container_name: ng-cash-backend
    build: ./ng-cash-backend
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./ng-cash-backend/.env.docker
    depends_on:
      - ng-cash-postgres-production

  ng-cash-frontend-application: 
    container_name: ng-cash-frontend
    build: 
      context: ./ng-cash-frontend
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - ng-cash-backend-application

volumes:
  postgres: